version: '3.6'

services:
  redis-rdb:
    image: redis:latest
    ports:
      - "63791:6379"
    volumes:
      - ./redis-rdb.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-aof:
    image: redis:latest
    ports:
      - "63792:6379"
    volumes:
      - ./redis-aof.conf:/usr/local/etc/redis/redis.conf
      - ./appendonlydir:/usr/local/etc/redis/appendonlydir
    command: redis-server /usr/local/etc/redis/redis.conf

  beanstalkd:
    image: schickling/beanstalkd:latest
    ports:
      - "11300:11300"

networks:
  application:
    driver: bridge